.PHONY: clean All

All:
	@echo "----------Building project:[ ValidParenthesesString - Debug ]----------"
	@cd "ValidParenthesesString" && "$(MAKE)" -f  "ValidParenthesesString.mk"
clean:
	@echo "----------Cleaning project:[ ValidParenthesesString - Debug ]----------"
	@cd "ValidParenthesesString" && "$(MAKE)" -f  "ValidParenthesesString.mk" clean
