.PHONY: clean All

All:
	@echo "----------Building project:[ WordBreak - Debug ]----------"
	@cd "WordBreak" && "$(MAKE)" -f  "WordBreak.mk"
clean:
	@echo "----------Cleaning project:[ WordBreak - Debug ]----------"
	@cd "WordBreak" && "$(MAKE)" -f  "WordBreak.mk" clean
