.PHONY: clean All

All:
	@echo "----------Building project:[ PartitionArrayIntoThreePartsWithEqualSum - Debug ]----------"
	@cd "PartitionArrayIntoThreePartsWithEqualSum" && "$(MAKE)" -f  "PartitionArrayIntoThreePartsWithEqualSum.mk"
clean:
	@echo "----------Cleaning project:[ PartitionArrayIntoThreePartsWithEqualSum - Debug ]----------"
	@cd "PartitionArrayIntoThreePartsWithEqualSum" && "$(MAKE)" -f  "PartitionArrayIntoThreePartsWithEqualSum.mk" clean
